CREATE TABLE XXUSER_RESPONSIBILITY_HEADER(
	REQUEST_ID NUMBER,
    REPORT_RUN_DATE DATE,
	GRE_NAME VARCHAR2(240),
	INSTANCE_NAME VARCHAR2(240),
	ORGANIZATION_D VARCHAR2(240),
	ORGANIZATION_TYPE VARCHAR2(30),
	TAB_NAME VARCHAR2(31)
);

CREATE TABLE XXUSER_RESPONSIBILITY_DETAIL(
    REQUEST_ID NUMBER,
	ORGANIZATION VARCHAR2(240),
	ORGANIZATION_TYPE VARCHAR2(30),
	USER_ID NUMBER(15),
	USER_NAME VARCHAR2(100),
    FULL_NAME VARCHAR2(240),
	EMPLOYEE_NUMBER VARCHAR2(30),
	FROM_EFFECTIVE_DATE_U DATE,
    TO_EFFECTIVE_DATE_U DATE,
	CREATED_BY NUMBER(15),
	CREATED_BY_NAME VARCHAR2(240),
	CREATION_DATE DATE,
	LAST_UPDATED_BY NUMBER(15),
	LAST_UPDATED_BY_NAME VARCHAR2(240),
	LAST_UPDATED_DATE DATE,
	RESPONSIBILITY_NAME VARCHAR2(100),
	APPLICATION_NAME VARCHAR2(240),
	SECURITY_GROUP VARCHAR2(80),
	FROM_EFFECTIVE_DATE_R DATE,
	TO_EFFECTIVE_DATE_R DATE,
	ASSIGNED_BY NUMBER(15),
	ASSIGNED_BY_NAME VARCHAR2(100),
	ASSIGNED_DATE DATE,
	ASSIGNMENT_UPDATED_BY NUMBER(15),
	ASSIGNMENT_UPDATED_BY_NAME VARCHAR2(240),
	ASSIGNMENT_UPDATED_DATE DATE
);